- name: Fix apt sources to use HTTPS
  ansible.builtin.copy:
    dest: /etc/apt/sources.list
    content: |
      deb https://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
      deb https://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
      deb https://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
      deb https://security.ubuntu.com/ubuntu jammy-security main restricted universe multiverse
    mode: '0644'

- name: Clean apt cache
  ansible.builtin.apt:
    clean: true

- name: Update apt cache with retries
  ansible.builtin.apt:
    update_cache: true
  register: common_apt_update
  retries: 5
  delay: 10
  until: common_apt_update is succeeded

- name: Ensure Python is installed
  ansible.builtin.raw: test -e /usr/bin/python3 || (apt update && apt install -y python3)
  changed_when: false

- name: Install base packages
  ansible.builtin.apt:
    name:
      - python3
      - python3-apt
      - curl
    state: present
