---
- name: Base infrastructure setup
  hosts: all
  become: true
  gather_facts: false
  roles:
    - common

- name: Gather facts after Python install
  hosts: all
  become: true
  gather_facts: true

- name: Configure app node
  hosts: app
  become: true
  gather_facts: true
  roles:
    - app
